# 核心训练参数
seed: 0
dataset_name: "ms"
do_train: true
load_model: "../save/scGPT_human"
epochs: 10
lr: 0.0001
batch_size: 128
schedule_ratio: 0.9
save_eval_interval: 5
amp: true
freeze: false
log_interval: 100
total_embs: "both"
# 模型结构参数
layer_size: 128
nlayers: 4
nhead: 4
dropout: 0.2
n_bins: 200
max_seq_len: 3001
fast_transformer: true
pre_norm: false

# 训练目标开关 (通常为布尔值)
MLM: false
CLS: true
ADV: false
CCE: false
MVC: false
ECS_enabled: false # 用一个布尔值控制ECS是否启用
DAB_enabled: false # 用一个布尔值控制DAB是否启用

# 其他特定目标参数
mask_ratio: 0.0
ecs_thres: 0.0
dab_weight: 0.0
DSBN: false
INPUT_BATCH_LABELS: false # 这个可能在你的原始代码中是硬编码的False，这里可以设置为True进行测试

# 其他不变的硬编码参数 (这些通常无需暴露给用户)
# max_seq_len: 20000
# input_style: "binned"
# output_style: "binned"
# input_emb_style: "continuous" # 注意，如果input_style是binned，这个应该对应category
# cell_emb_style: "cls"
# adv_E_delay_epochs: 0
# adv_D_delay_epochs: 0
# mvc_decoder_style: "inner product"
# lr_ADV: 0.001
# schedule_interval: 1
# fast_transformer_backend: "flash"
# do_eval_scib_metrics: true
# data_dir: "../data/ms"